ArtiblogzFinal/config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :users

  resources :topics do
    resources :comments
  end

end

ArtiblogzFinal/app/models/topic.rb
class Topic < ActiveRecord::Base
  default_scope { order(created_at: :DESC) }

  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true,
                    length: { maximum: 50 }
  validates :content, presence: true,
                      length: { maximum: 140 }
end

ArtiblogzFinal/app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # force_ssl

  before_filter :authorize, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :authorization]
  before_action :authorization, only: [:edit, :update, :destroy]

  def index
    # response.headers['Link'] = 'topics'
    @topics = Topic.all
  end

  def show
    # response.headers['Link'] = 'topic'
  end

  def new
    # response.headers['Link'] = 'new_topic'
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id
    @user = User.find(current_user.id)
    @topic.username = @user.username
    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic created.' }
        format.json { render :show, status: 201, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: 422 }
      end
    end
  end

  def edit
    # response.headers['Link'] = 'edit_topic'
  end

  def update
    respond_to do |format|
      if @topic.nil?
        fail ActiveRecord::RecordNotFound
      elsif @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic updated.' }
        format.json { render :show, status: 200, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: 422 }
      end
    end
  end

  def destroy
    if @topic.nil?
      fail ActiveRecord::RecordNotFound
    else
      @topic.destroy
      respond_to do |format|
        format.html { redirect_to topics_path(@topic), notice: 'Topic deleted.' }
        format.json { head :no_content, status: 204 }
      end
    end
  end

  rescue_from ActiveRecord::RecordNotFound do
    render :topic_missing, status: 404
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :content) if params[:topic]
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end

  def authorization
    redirect_to topics_path, notice: "You can't do that !" unless current_user.id == @topic.user_id
  end
end

ArtiblogzFinal/app/helpers/topics_helper.rb
module TopicsHelper
end

ArtiblogzFinal/app/views/topics/_form.html.erb
<%= form_for @topic do |f| %>
<% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@topic.errors.count, "error") %> prohibited this article
        from being saved:
      </h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>Title :</strong><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <strong>Content :</strong><br>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

ArtiblogzFinal/app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

ArtiblogzFinal/app/views/topics/index.html.erb
<p id='notice'><%= notice %></p>

<h2>Listing topics</h2>

<table>
  <thead>
    <tr>
      <td>Title</td>
      <td>Created by @ Created at</td>
    </tr>
  </thead>
  <% @topics.each do |topic| %>
    <tr>
      <td><%= link_to topic.title, topic_path(topic) %></td>
      <td><%= link_to topic.username, user_path(topic.user_id) %>@<%= topic.created_at.strftime('%F %R') %></td></tr>
    </tr>
  <% end %>
</table>
<br>

<% unless current_user.nil? %>
  <%= link_to 'New Topic', new_topic_path %>
<% end %>

ArtiblogzFinal/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

ArtiblogzFinal/app/views/topics/show.html.erb
<p id='notice'><%= notice %></p>
<p>
  <strong><%= @topic.title %></strong> :
  <%= link_to @topic.username, user_path(@topic.user_id) %>@<%= @topic.created_at.strftime('%F %R') %><br>
</p>

<%= @topic.content %><br><br>

<% unless current_user.nil? %>
  <% if current_user.id == @topic.user_id %>
    <%= link_to 'Edit', edit_topic_path(@topic) %>
    <%= link_to 'Delete', topic_path(@topic), method: :delete, data: { confirm: 'Are you sure ?' } %>
  <% end %>
<% end %>

<h2>Comments :</h2>

<%= render @topic.comments  %>

<% unless current_user.nil? %>
  <h2>Add a comment :</h2>
  <%= render 'comments/form' %>
<% end %>

ArtiblogzFinal/app/views/topics/topic_missing.erb
Topic Not Found